// lib/services/contact_sync_service.dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:nudge/services/api_service.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:contacts_service/contacts_service.dart' as contact_service;
import '../models/contact.dart';

class ContactSyncService {
  final ApiService apiService;

  ContactSyncService({required this.apiService});

  Future<Map<String, dynamic>> importDeviceContacts({
    required Function(int processed, int total) onProgress,
  }) async {
    try {
      // Check and request permission
      var status = await Permission.contacts.status;
      if (!status.isGranted) {
        status = await Permission.contacts.request();
        if (!status.isGranted) {
          return {
            'success': false,
            'message': 'Contacts permission denied',
            'importedCount': 0
          };
        }
      }

      // Get device contacts
      List<contact_service.Contact> deviceContacts = 
          await contact_service.ContactsService.getContacts();
      
      final currentUser = FirebaseAuth.instance.currentUser;
      if (currentUser == null) {
        return {
          'success': false,
          'message': 'User not logged in',
          'importedCount': 0
        };
      }

      int importedCount = 0;
      int processedCount = 0;
      int totalContacts = deviceContacts.length;
      
      // Get reference to user's contacts subcollection
      final contactsRef = FirebaseFirestore.instance
          .collection('users')
          .doc(currentUser.uid)
          .collection('contacts');

      // Process contacts in batches
      const batchSize = 400; // Stay under Firestore's 500 operations per batch limit
      WriteBatch batch = FirebaseFirestore.instance.batch();
      
      for (var deviceContact in deviceContacts) {
        processedCount++;
        
        // Update progress
        onProgress(processedCount, totalContacts);
        
        // Skip contacts without names
        if (deviceContact.displayName == null || deviceContact.displayName!.isEmpty) {
          continue;
        }

        // Create Nudge contact from device contact
        Contact nudgeContact = Contact(
          id: '', // Will be generated by Firestore
          name: deviceContact.displayName ?? 'Unknown',
          phoneNumber: deviceContact.phones?.isNotEmpty == true 
              ? deviceContact.phones!.first.value ?? '' 
              : '',
          email: deviceContact.emails?.isNotEmpty == true 
              ? deviceContact.emails!.first.value ?? '' 
              : '',
          connectionType: 'Friend', // Default
          frequency: 2, // Default
          period: 'Monthly',
          socialGroups: [],
          notes: '',
          imageUrl: deviceContact.avatar != null && deviceContact.avatar!.isNotEmpty
              ? 'data:image/png;base64,${String.fromCharCodes(deviceContact.avatar!)}' 
              : '',
          lastContacted: DateTime.now(),
          isVIP: false,
          priority: 3,
          tags: [],
          interactionHistory: {},
        );

        // Add to batch
        final docRef = contactsRef.doc(); // Auto-generated ID
        batch.set(docRef, nudgeContact.toMap());
        importedCount++;

        // Commit batch when we reach batch size
        if (importedCount % batchSize == 0) {
          await batch.commit();
          batch = FirebaseFirestore.instance.batch(); // Start new batch
        }
      }

      // Commit any remaining operations
      if (importedCount % batchSize != 0) {
        await batch.commit();
      }

      return {
        'success': true,
        'message': 'Successfully imported $importedCount contacts',
        'importedCount': importedCount
      };
    } catch (e) {
      return {
        'success': false,
        'message': 'Failed to import contacts: $e',
        'importedCount': 0
      };
    }
  }
}