// lib/services/nudge_service.dart
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:nudge/services/api_service.dart';
// import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;
import 'dart:io';
import '../models/contact.dart';
import '../models/nudge.dart';
// import '../services/database_service.dart';
import '../services/notification_service.dart';

class NudgeService {
  static final NudgeService _instance = NudgeService._internal();
  final FlutterLocalNotificationsPlugin notificationsPlugin =
      FlutterLocalNotificationsPlugin();
  final NotificationService _notificationService = NotificationService();

  factory NudgeService() {
    return _instance;
  }

  NudgeService._internal();

  Future<void> initialize() async {
    tz.initializeTimeZones();
    
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');

    const DarwinInitializationSettings initializationSettingsIOS =
        DarwinInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: true,
      requestSoundPermission: true,
    );

    const InitializationSettings initializationSettings =
        InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
    );

    await notificationsPlugin.initialize(initializationSettings);
    
    // Initialize notification service
    await _notificationService.initialize();
    
    // Request notification permissions
    await _requestNotificationPermissions();
  }

  Future<void> _requestNotificationPermissions() async {
    if (Platform.isAndroid) {
      // For Android 13+, we need to request notification permission
      // final status = await Permission.notification.request();
    }
  }

  Future<void> scheduleNudgeForContact(Contact contact, String userId) async {
      // Calculate next nudge time based on frequency
      DateTime nextNudgeTime = _calculateNextNudgeTime(contact);
      
      // Create a nudge object
      final nudge = Nudge(
        id: '', // Will be generated by ApiService
        contactId: contact.id,
        contactName: contact.name,
        nudgeType: 'followup',
        message: 'Time to connect with ${contact.name}',
        scheduledTime: nextNudgeTime,
        userId: userId,
      );
      
      // Save using ApiService
      final apiService = ApiService();
      await apiService.addNudge(nudge);
      
      // Schedule notification
      await _notificationService.scheduleNudgeNotification(
        contact.id.hashCode,
        'Time to connect!',
        'Remember to reach out to ${contact.name}',
        nextNudgeTime,
      );
      
      // Update contact's last nudge time
      print('Nudge scheduled for ${contact.name} at $nextNudgeTime');
    }


  DateTime _calculateNextNudgeTime(Contact contact) {
    DateTime now = DateTime.now();
    
    switch (contact.frequency) {
      case 'Weekly':
        return now.add(const Duration(days: 7));
      case 'Monthly':
        return now.add(const Duration(days: 30));
      case 'Quarterly':
        return now.add(const Duration(days: 90));
      case 'Annually':
        return now.add(const Duration(days: 365));
      default:
        return now.add(const Duration(days: 30));
    }
  }

  Future<void> scheduleAllNudges(List<Contact> contacts, String userId) async {
    for (var contact in contacts) {
      await scheduleNudgeForContact(contact, userId);
    }
  }

  Future<void> cancelNudge(int id) async {
    await notificationsPlugin.cancel(id);
  }

  Future<void> cancelAllNudges() async {
    await notificationsPlugin.cancelAll();
  }
}